development:
  adapter: postgresql
  encoding: unicode
  database: gecko4_development
  pool: 5
  username: postgres
  password: 123123123
  host: 192.168.59.103

test:
  adapter: postgresql
  encoding: unicode
  database: gecko4_test
  pool: 5
  username: postgres
  password: 123123123
  host: 192.168.59.103

production:
  adapter: postgresql
  encoding: unicode
  database: gecko4_production
  pool: 5
  username: postgres
  password: 123123123
  host: db