# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e7bf952bb2ebd44af67ef60309b6d0238fecbaa85c035e367851482ee2bd84b784c1f3856ea57fc8f5383c7040fcb203e913ad444d3d169cbae58a23974f76

test:
  secret_key_base: 802ec4529bb062600f017757c4a424b443955e3060e7d24c0461fe034b52b87d89262ac5fb2374c272ba2b04bb22ce687baa1e98930bfc778d889d17af0660eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
